/*
 * app_config.h - central configuration.
 *
 * Values come from `idf.py menuconfig` -> "WellHouse Configuration" (see
 * Kconfig.projbuild). The #ifndef fallbacks keep the tree building and editors
 * happy before menuconfig has been run.
 */
#pragma once

#include "sdkconfig.h"
#include "driver/spi_master.h"

#define APP_FW_VERSION "1.0.0"

/* ---- Identity / network ---- */
#ifndef CONFIG_WELLHOUSE_DEVICE_ID
#define CONFIG_WELLHOUSE_DEVICE_ID "device-01"
#endif
#ifndef CONFIG_WELLHOUSE_MQTT_BROKER_URI
#define CONFIG_WELLHOUSE_MQTT_BROKER_URI "mqtt://192.168.0.10:1883"
#endif
#ifndef CONFIG_WELLHOUSE_MQTT_USERNAME
#define CONFIG_WELLHOUSE_MQTT_USERNAME "water1"
#endif
#ifndef CONFIG_WELLHOUSE_MQTT_PASSWORD
#define CONFIG_WELLHOUSE_MQTT_PASSWORD ""
#endif
#ifndef CONFIG_WELLHOUSE_WIFI_SSID
#define CONFIG_WELLHOUSE_WIFI_SSID "son"
#endif
#ifndef CONFIG_WELLHOUSE_WIFI_PASSWORD
#define CONFIG_WELLHOUSE_WIFI_PASSWORD "33483348"
#endif
#ifndef CONFIG_WELLHOUSE_SNTP_SERVER
#define CONFIG_WELLHOUSE_SNTP_SERVER "pool.ntp.org"
#endif

#define APP_DEVICE_ID       CONFIG_WELLHOUSE_DEVICE_ID
#define APP_MQTT_BROKER_URI CONFIG_WELLHOUSE_MQTT_BROKER_URI
#define APP_MQTT_USERNAME   CONFIG_WELLHOUSE_MQTT_USERNAME
#define APP_MQTT_PASSWORD   CONFIG_WELLHOUSE_MQTT_PASSWORD
#define APP_WIFI_SSID       CONFIG_WELLHOUSE_WIFI_SSID
#define APP_WIFI_PASSWORD   CONFIG_WELLHOUSE_WIFI_PASSWORD
#define APP_SNTP_SERVER     CONFIG_WELLHOUSE_SNTP_SERVER

/* ---- Timing / storage ---- */
#ifndef CONFIG_WELLHOUSE_HEARTBEAT_MS
#define CONFIG_WELLHOUSE_HEARTBEAT_MS 30000
#endif
#ifndef CONFIG_WELLHOUSE_WATER_PUBLISH_MS
#define CONFIG_WELLHOUSE_WATER_PUBLISH_MS 2000
#endif
#ifndef CONFIG_WELLHOUSE_CMD_HOLD_MS
#define CONFIG_WELLHOUSE_CMD_HOLD_MS 10000
#endif
#ifndef CONFIG_WELLHOUSE_UTC_OFFSET_MIN
#define CONFIG_WELLHOUSE_UTC_OFFSET_MIN 540   /* KST = UTC+9 */
#endif
#ifndef CONFIG_WELLHOUSE_EVENT_QUEUE_CAP
#define CONFIG_WELLHOUSE_EVENT_QUEUE_CAP 64
#endif

#define APP_HEARTBEAT_MS      CONFIG_WELLHOUSE_HEARTBEAT_MS
#define APP_WATER_PUBLISH_MS  CONFIG_WELLHOUSE_WATER_PUBLISH_MS
#define APP_CMD_HOLD_MS       CONFIG_WELLHOUSE_CMD_HOLD_MS
#define APP_UTC_OFFSET_MIN    CONFIG_WELLHOUSE_UTC_OFFSET_MIN
#define APP_EVENT_QUEUE_CAP   CONFIG_WELLHOUSE_EVENT_QUEUE_CAP

/* ---- Water: ADC -> cm mapping + risk-state thresholds (raw ADC) ---- */
#ifndef CONFIG_WELLHOUSE_WATER_ADC_ZERO
#define CONFIG_WELLHOUSE_WATER_ADC_ZERO 500
#endif
#ifndef CONFIG_WELLHOUSE_WATER_ADC_PER_CM
#define CONFIG_WELLHOUSE_WATER_ADC_PER_CM 300
#endif
#ifndef CONFIG_WELLHOUSE_THR_WARNING
#define CONFIG_WELLHOUSE_THR_WARNING 500
#endif
#ifndef CONFIG_WELLHOUSE_THR_ALERT
#define CONFIG_WELLHOUSE_THR_ALERT 1200
#endif
#ifndef CONFIG_WELLHOUSE_THR_DANGER
#define CONFIG_WELLHOUSE_THR_DANGER 2500
#endif

#define APP_WATER_ADC_ZERO    CONFIG_WELLHOUSE_WATER_ADC_ZERO
#define APP_WATER_ADC_PER_CM  CONFIG_WELLHOUSE_WATER_ADC_PER_CM
#define APP_THR_WARNING       CONFIG_WELLHOUSE_THR_WARNING
#define APP_THR_ALERT         CONFIG_WELLHOUSE_THR_ALERT
#define APP_THR_DANGER        CONFIG_WELLHOUSE_THR_DANGER

/* ---- SPI link to STM (ESP32 = master, 3-byte exchange) ---- */
#ifndef CONFIG_WELLHOUSE_SPI_MISO
#define CONFIG_WELLHOUSE_SPI_MISO 19
#endif
#ifndef CONFIG_WELLHOUSE_SPI_MOSI
#define CONFIG_WELLHOUSE_SPI_MOSI 23
#endif
#ifndef CONFIG_WELLHOUSE_SPI_SCLK
#define CONFIG_WELLHOUSE_SPI_SCLK 18
#endif
#ifndef CONFIG_WELLHOUSE_SPI_CS
#define CONFIG_WELLHOUSE_SPI_CS 5
#endif
#ifndef CONFIG_WELLHOUSE_SPI_CLOCK_HZ
#define CONFIG_WELLHOUSE_SPI_CLOCK_HZ 1000000
#endif
#ifndef CONFIG_WELLHOUSE_SPI_POLL_MS
#define CONFIG_WELLHOUSE_SPI_POLL_MS 100
#endif

#define APP_SPI_HOST       SPI2_HOST
#define APP_SPI_MISO       CONFIG_WELLHOUSE_SPI_MISO
#define APP_SPI_MOSI       CONFIG_WELLHOUSE_SPI_MOSI
#define APP_SPI_SCLK       CONFIG_WELLHOUSE_SPI_SCLK
#define APP_SPI_CS         CONFIG_WELLHOUSE_SPI_CS
#define APP_SPI_CLOCK_HZ   CONFIG_WELLHOUSE_SPI_CLOCK_HZ
#define APP_SPI_POLL_MS    CONFIG_WELLHOUSE_SPI_POLL_MS
